### ISSUE TITLE
What is the vimspectr equivalent of stormpetrel?

### ISSUE THREAD

**Issue by babygau** [nightsense/vimspectr#1]
Hi, coming from `seabird` repo. I'm using the wonderful `stormpetrel` but couldn't find one of vimspectr.

**Comment by nightsense** [comment]
Hi @babygau , try `vimspectr210wcurve-dark`. If you find it doesn't work as well as `stormpetrel` for you, feel free to let me know why not and maybe I can add some adjustment options.

I've edited the seabird readme to clarify equivalent themes for anyone switching over to vimspectr from seabird.

**Comment by babygau** [comment]
Sadly, the color are not what I expected, please see the screenshot below for your own judgement:

**stormpetrel**
<img width="2672" alt="screenshot 2017-11-11 20 06 10" src="https://user-images.githubusercontent.com/1514823/32688006-a3cd7d1c-c71c-11e7-919e-047db779fa25.png">

**vimspectr210wcurve-dark**
<img width="2672" alt="screenshot 2017-11-11 20 08 41" src="https://user-images.githubusercontent.com/1514823/32688010-b1ad74f0-c71c-11e7-9b58-37cb3fd6c9ed.png">

Moreover, as you can see, the new colorscheme is unable to display italic font (comment, string...)

**Comment by nightsense** [comment]
OK, I've added some options and adjusted the saturation levels a bit. See what you think of:

```
let g:vimspectr210wcurve_dark_MuteAccents = 'on'
let g:vimspectr210wcurve_dark_MuteStatusLine = 'on'
let g:vimspectr210wcurve_dark_MuteLineNr = 'on'
let g:vimspectr210wcurve_dark_ItalicComment = 'on'
color vimspectr210wcurve-dark
```

**Comment by babygau** [comment]
@nightsense, 
`Italic font` is back, but the color is still quite right for me, specifically the background color, pls see below:
<img width="2672" alt="screenshot 2017-11-12 11 51 09" src="https://user-images.githubusercontent.com/1514823/32694879-f2df5bb8-c79f-11e7-8186-7525e44c02c8.png">
