### ISSUE TITLE
How can you generate the color palettes?

### ISSUE THREAD

**Issue by lifepillar** [nightsense/vimspectr#2]
Cool colorschemes! Would you share how you create the color palettes based on hue and saturation (formulas or script)?

I'd like to extend my [Colortemplate](https://github.com/lifepillar/vim-colortemplate) plugin by adding functions that generate good-looking palettes.

**Comment by nightsense** [comment]
Sure thing, I use a little [python script](https://gist.github.com/nightsense/2dd5403cb53891e9ec1c337b0989ff9b). WARNING: I am just an amateur who enjoys cobbling things together that others might find useful; actual python programmers may be horrified by this script. :scream:

**Comment by lifepillar** [comment]
Thanks, that's very much appreciated!

**Comment by lifepillar** [comment]
Your script outputs eight colors, but your colorschemes use sixteen colors plus muted accents. Which parameters do you use for the remaining eight colors and for the muted accents?

**Comment by lifepillar** [comment]
Btw, I have included a Vim version of your generating script in [Colortemplate](https://github.com/lifepillar/vim-colortemplate).

**Comment by nightsense** [comment]
I just hand-picked those colours by eye, nudging around HSV values by discrete jumps (e.g. nudging hue 7.5 degrees at a time). To ensure a minimum text/background contrast ratio of 3:1 (which is only really an issue with light backgrounds) for each accent colour, I just performed manual checks.

There are only four sets of accent colours: a "regular accent set" and "muted accent set" for dark-background themes, and likewise for light-background themes. So for instance, all dark-background themes use the same set of eight regular accent colours, or (if the "muted accent" option is active) the same set of eight muted accent colours.

(Right now the muted accent sets are basically rough placeholders; I'll be refining them when I find the time.)

I am watching Colortemplate with interest!
