### ISSUE TITLE
git diffs use wrong colors

### ISSUE THREAD

**Issue by evantravers** [nightsense/vimspectr#3]
This is using vimspectr60flat-dark… I guess because it's all automagically defined, there are some overlaps. One very important aspect of a colorscheme to me is that the diffs are relatively traditionally defined… green-ish for addition, red-ish for deletion, yellow-ish for modified. I suppose I can add custom variables for it, but I thought I'd bring it to your attention.

Thanks for such a neat project, I do like it quite a lot so far.

<img width="726" alt="screen shot 2017-11-27 at 5 54 27 am" src="https://user-images.githubusercontent.com/62209/33265464-7809a9f4-d337-11e7-802c-a6e8165030f6.png">

**Comment by evantravers** [comment]
Doing some reading… I *think* the desired highlight groups are:

```vim
hi! link gitcommitSelectedFile <green>
hi! link gitcommitDiscardedFile <red>
```

**Comment by nightsense** [comment]
Thanks for letting me know (and providing the highlight groups too :+1: ), that should be fixed now. Do send along any future issues/suggestions. Glad you like the themes! :frog:

**Comment by evantravers** [comment]
This looks great, thanks!
