### ISSUE TITLE
Cannot get colors to display correctly

### ISSUE THREAD

**Issue by adamtaylor13** [nightsense/vimspectr#4]
I'm having a lot of difficulty getting my colors to display correctly and I'm also not having a lot of luck finding resources to resolve it. I want to preface this issue by stating: _I don't think it's an issue with this package_. I just hope perhaps this might help someone else later on.

I've created the symlink, I've updated the plugin and uninstalled/re-installed a couple of times, I've also checked to make sure that my terminal has 256 colors enabled.

I'm on a Macbook Pro 2016, and I'm using the default Terminal.app, not iTerm2. For reasons beyond me, my computer gripes at me and says I can't use it "with macs of this type".

Currently I'm getting this color on _any_ vimspectr theme (including the separate seagrey theme!):

![image](https://user-images.githubusercontent.com/2922753/38035281-ad58a6dc-3269-11e8-9f0f-0cfcf6e0cfc0.png)

I feel like the fact that _all_ vimspectr themes revert to this default color is a clue of some sort but I just can't crack what's up.

Any help is greatly appreciated—my eyes are bleeding.

P.S. My Terminal Colors settings look like this and it seems like my vim colorscheme might be using these colors for some reason?

![image](https://user-images.githubusercontent.com/2922753/38035398-f0b7e262-3269-11e8-8094-a5a983f6a08f.png)

**Comment by nightsense** [comment]
Hi @adamtaylor13 , thanks for reporting. I'll look into this as soon as I can steal someone's macbook for a while.

If you don't mind messing around a bit more, try installing my [shoji](https://github.com/nightsense/shoji) theme to see if the colors come out right. I generated that theme using lifepillar's [Colortemplate](https://github.com/lifepillar/vim-colortemplate) utility, which is now arguably the gold standard for vim theme generation. I've been contemplating using Colortemplate to reimplement vimspectr, and if shoji works nicely for you, that may be the tipping point.

**Comment by adamtaylor13** [comment]
Hey I appreciate the quick reply! I followed standard procedure:
- Install Plugin
- Change `colorscheme shoji_niji`
- Save `.vimrc` close it, and restart it.

I got this:
![image](https://user-images.githubusercontent.com/2922753/38056268-aed1d79e-32a1-11e8-9815-28194eec9dd2.png)

It's closer than the other themes, but it does appear to still be a bit off. :(

Again, thanks for the quick reply & let me know how else I can be of assistance!

**Comment by nightsense** [comment]
It looks like it isn't possible to support Terminal.app with a color-setting shell script, according to [this issue](https://github.com/chriskempson/base16-shell/issues/2) in the base16-shell repository. (The vimspectr shell script template is just a lightly-modified version of base16-shell.)  Instead you've got to import a profile, like those created for base16 [here](https://github.com/vbwx/base16-terminal-app).

I don't plan to extend vimspectr with Terminal.app profiles, at least not in the short term (no time! :hourglass_flowing_sand::grimacing:), but if anyone were to do so I would gladly link to their repo. Sorry I can't be more helpful at the moment.

**Comment by adamtaylor13** [comment]
Hey no problem! Thanks for the help diagnosing the problem. I switched to iTerm2 and the issue is resolved. It does indeed seem to be a Terminal.app issue.

Thanks for all the hard work!
