### ISSUE TITLE
Weird backgrounds

### ISSUE THREAD

**Issue by filipekiss** [nightsense/vimspectr#5]
Hey, first of all thank you for all these themes! They are great. Unfortunately, I'm having some trouble with it.

Here's how Gruvbox behaves:

![image](https://user-images.githubusercontent.com/48519/41470047-c6890a7a-7085-11e8-9f85-67e8d9b6f9b0.png)

Here's how it displays using any nightsense theme:

![image](https://user-images.githubusercontent.com/48519/41470078-de30a2fa-7085-11e8-8c99-d91e983c3a3b.png)

I've tried either disabling `termiguicolors` (which make the theme look worse):

![image](https://user-images.githubusercontent.com/48519/41470105-f48a2e04-7085-11e8-93c2-e8bbb2002c23.png)

And running `tmux -2` also doesn't work (renders as the second screenshot from the top).

I'm using the vimspectr shell scripts to set  my terminal color and i'm using iTerm 2 (but I tried this with Kitty terminal as well and the result is the same).

Can you point what I am doing wrong?

Thank you!

**Comment by nightsense** [comment]
You're welcome! :frog: 

I don't know offhand what's going wrong there. Sorry about the issue, I might mess around with it later, but I'm actually planning on rebuilding the vimspectr themes soon using [Colortemplate](https://github.com/lifepillar/vim-colortemplate), which produces themes that work nicely in the terminal without the mess of shell scripts. So in that sense, a fix is on the (eventual) way!

**Comment by filipekiss** [comment]
Great to hear! Thankyou @nightsense! I’ll fiddle around and see if I can manage to find out why this happens :)

**Comment by filipekiss** [comment]
And if you need help rewriting the themes, let me know! I’d love to help.
